Repository petekostrytsya/DevHunt, pull requests merged in 2023-01, with the labels that each got.

#48 about-class-js-open-modal
  src/partials/about.html
Labels: enhancement

#46 Класи для модалок на кнопки
  src/partials/contacts.html
Labels: enhancement

#43 add animation to icon
  src/sass/_footer.scss
Labels: enhancement, good first issue

#60 add button to top
  src/images/arrow.svg
  src/index.html
  src/index.js
  src/js/arrow_to_top.js
  src/partials/arrow_to_top.html
  src/sass/_arrow_to_top.scss
  src/sass/index.scss
Labels: enhancement

#64 add animate
  src/partials/about.html
  src/partials/advantages.html
  src/partials/contacts.html
  src/partials/header.html
  src/partials/products.html
Labels: good first issue

#38 Modal ingredients+ modal-product-card
  src/index.html
  src/index.js
  src/js/arrow_to_top.js
  src/js/validation-highlight.js
  src/partials/header.html
  src/partials/modal-ingredients.html
  src/partials/modal-product-card.html
  src/partials/products.html
  src/sass/_contacts.scss
  src/sass/_cursor.scss
  src/sass/_hero.scss
  src/sass/_modal-all.scss
  src/sass/_modal-ingredients.scss
  src/sass/_modal-product-card.scss
  src/sass/_reset.scss
Labels: good first issue
